apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: kube-controller-manager
    app.kubernetes.io/part-of: kube-prometheus
  name: kube-controller-manager-service
  namespace: kube-system
spec:
  ports:
  - name: client
    port: 10257
    targetPort: 10257
    protocol: TCP
  selector:
    component: kube-controller-manager
    tier: control-plane
  type: ClusterIP