apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: kube-proxy
    app.kubernetes.io/part-of: kube-prometheus
  name: kube-proxy-service
  namespace: kube-system
spec:
  ports:
  - name: client
    port: 10249
    targetPort: 10249
    protocol: TCP
  selector:
    k8s-app: kube-proxy
  type: ClusterIP