apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: kube-scheduler
    app.kubernetes.io/part-of: kube-prometheus
  name: kube-scheduler-service
  namespace: kube-system
spec:
  ports:
  - name: client
    port: 10259
    targetPort: 10259
    protocol: TCP
  selector:
    component: etcd
    tier: control-plane
  type: ClusterIP